OUTPUT_DIR: "./exps/maiou/prw_oim++_mini_3"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "./datasets/PRW_MINI_2"
MODEL:
  LOSS:
    TYPE: 'LOIM'
    OIM_EPS: 0.1
    LUT_SIZE: 482
    CQ_SIZE: 500
  ROI_HEAD:
    NORM_TYPE: 'protonorm'
