OUTPUT_DIR: "./exps/PRW_VOC_MIX/1"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "./datasets/PRW_SEG_VOC_MIX"
MODEL:
  LOSS:
    TYPE: 'LOIM'
    OIM_EPS: 0.1
    LUT_SIZE: 482
    CQ_SIZE: 500
  ROI_HEAD:
    NORM_TYPE: 'protonorm'
