OUTPUT_DIR: "./exps/prw_oim_seg_1"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "./datasets/PRW_seg"
MODEL:
  LOSS:
    TYPE: 'LOIM'
    OIM_EPS: 0.1
    LUT_SIZE: 482
    CQ_SIZE: 500
  ROI_HEAD:
    NORM_TYPE: 'protonorm'
